### ISSUE TITLE
Put gradle quickstart into readme

### ISSUE THREAD

**Issue by CRogers** [palantir/streams#1]
I have no idea where the published artifacts for this project live. Consider having a section in the readme saying where to get this library from (maybe some gradle code too to show this)?

**Comment by j-baker** [comment]
Ack. Will sort this out tomorrow. For reference, library currently lives at com.palantir.commons:streams:1.0.3
On Sat, 20 Feb 2016 at 14:49, Callum Rogers <notifications@github.com<mailto:notifications@github.com>> wrote:

I have no idea where the published artifacts for this project live. Consider having a section in the readme saying where to get this library from (maybe some gradle code too to show this)?

**Comment by cjp39** [comment]
We should just link to the current artifact with a badge. Keeping the versions up-to-date is a royal PITA. e.g. https://maven-badges.herokuapp.com/maven-central/com.palantir.common/streams/badge.svg?style=plastic would work if we were on Maven Central (which we should be??)

**Comment by j-baker** [comment]
Maven central is another thing i should get around to today. Last time I tried it I got scared off.

On Sun, 21 Feb 2016 at 01:45, Chris Purcell <notifications@github.com<mailto:notifications@github.com>> wrote:

We should just link to the current artifact with a badge. Keeping the versions up-to-date is a royal PITA. e.g. https://maven-badges.herokuapp.com/maven-central/com.palantir.common/streams/badge.svg?style=plastic would work if we were on Maven Central (which we should be??)

**Comment by j-baker** [comment]
Update. Maven central stuff was set up manually by someone who's no longer on Rainbow. I've been asked to file a ticket. Will keep updated.

In the meantime, is jcenter enough? giving the badge below.

  [ ![Download](https://api.bintray.com/packages/palantir/releases/streams/images/download.svg) ](https://bintray.com/palantir/releases/streams/_latestVersion)

**Comment by cjp39** [comment]
Yep, let's go with that. Thanks!

**Comment by cjp39** [comment]
Fixed by #2
