### ISSUE TITLE
Add a method `mapVals` and/or `mapValues`

### ISSUE THREAD

**Issue by mlgamble** [palantir/streams#18]
To improve readability, it would be nice to not rely on a dev's knowledge of the library that `map` actually means mapping the values.

So that I can have code that looks like

`KeyedStream.of(getAllUsers)
    .mapKeys(User::getUsername)
    .mapVals(User::isUserOnline)
`

**Comment by chrisalice** [comment]
Did you consider using [streamex] instead? They made the API decision to model it as a stream of entries rather than a stream of values with keys attached.

[streamex]: http://amaembo.github.io/streamex/javadoc/one/util/streamex/EntryStream.html

**Comment by mlgamble** [comment]
Neat! Thanks
