### ISSUE TITLE
Can we upgrade Guava?

### ISSUE THREAD

**Issue by jnelson15** [palantir/streams#22]
We have guava runtime at 18.0, I assume due to usage in our products. What would it take to upgrade? If we're able to take 23.1+, we could create pre-sized ImmutableList/Map/Set collectors (see https://github.com/google/guava/blob/v23.1/guava/src/com/google/common/collect/ImmutableList.java#L728), which could reduce a lot of unnecessary resizing when people are doing simple things like maps where they necessarily know the size of the resulting collection. For example we could add something like the following to `MoreCollectors`:
```
    public static <T> Collector<T, ?, List<T>> toImmutableList(int expectedSize) {
        return Collector.of(
                () -> ImmutableList.<T>builderWithExpectedSize(expectedSize),
                ImmutableList.Builder::<T>add,
                (left, right) -> left.addAll(right.build()),
                ImmutableList.Builder::build);
    }
```

**Comment by chrisalice** [comment]
Why not use `ImmutableList.toImmutableList`? The stream will propagate the size information already.

**Comment by jnelson15** [comment]
Because the old builder uses an array of size `DEFAULT_INITIAL_CAPACITY = 4`. So this could result in multiple array resizes when adding elements to it.

**Comment by jnelson15** [comment]
From 21.0:
```
  @Beta
  public static <E> Collector<E, ?, ImmutableList<E>> toImmutableList() {
    return CollectCollectors.toImmutableList();
  }
```
```
  static <E> Collector<E, ?, ImmutableList<E>> toImmutableList() {
    return Collector.of(
        ImmutableList::<E>builder,
        ImmutableList.Builder::add,
        ImmutableList.Builder::combine,
        ImmutableList.Builder::build);
  }
```
```
  public static <E> Builder<E> builder() {
    return new Builder<E>();
  }
```
```
    public Builder() {
      this(DEFAULT_INITIAL_CAPACITY);
    }

    // TODO(lowasser): consider exposing this
    Builder(int capacity) {
      super(capacity);
    }
```

**Comment by chrisalice** [comment]
Oh, right, because stream collection was designed to be concurrent so the estimated size is not passed into the collector.

Do you have benchmarks showing a noticeable speedup from this? It's not worth the readability and maintenance cost imo. (A function that takes the stream and uses the estimated size would be better, though still less readable than a vanilla collector.)

**Comment by jnelson15** [comment]
Don't have numbers at the moment but will follow up with that

**Comment by jnelson15** [comment]
@chrisalice here's some results from some JMH runs on
```
list.stream().collect(Collectors.toList());
```
vs
```
list.stream().collect(toImmutableList(size));
```
<img width="637" alt="screen shot 2017-10-24 at 10 07 28 am" src="https://user-images.githubusercontent.com/4187816/31947908-6f9f61e0-b8a3-11e7-96bc-5780e27dd5d2.png">

**Comment by jnelson15** [comment]
Note also this will reduce memory usage a fair amount given that it only has to allocate a single array rather than doing multiple resizes. Given this is a pretty common workflow (e.g. mapping Atlas rows) think this could be pretty valuable.

**Comment by j-baker** [comment]
Can we get some absolute numbers here? It's easy to for example recommend for loops as being faster than streams in general (frequently 2x faster to use for loops for example) but the performance difference is basically unimportant.

**Comment by jnelson15** [comment]
Benchmark                       Mode  Cnt         Score         Error  Units
GuavaTest.run_1000000_sized    thrpt   20       152.526 ±       3.222  ops/s
GuavaTest.run_1000000_unsized  thrpt   20       134.028 ±       7.265  ops/s
GuavaTest.run_100000_sized     thrpt   20      1871.684 ±     927.852  ops/s
GuavaTest.run_100000_unsized   thrpt   20      1459.130 ±     125.509  ops/s
GuavaTest.run_10000_sized      thrpt   20     52041.634 ±     977.906  ops/s
GuavaTest.run_10000_unsized    thrpt   20     15059.464 ±     531.821  ops/s
GuavaTest.run_1000_sized       thrpt   20    463978.811 ±   15649.220  ops/s
GuavaTest.run_1000_unsized     thrpt   20    142316.475 ±    6064.783  ops/s
GuavaTest.run_100_sized        thrpt   20   3820067.098 ±  132078.860  ops/s
GuavaTest.run_100_unsized      thrpt   20   1593746.619 ±   54334.566  ops/s
GuavaTest.run_10_sized         thrpt   20  12016242.166 ± 1077338.458  ops/s
GuavaTest.run_10_unsized       thrpt   20  12433768.165 ±  606091.095  ops/s

**Comment by j-baker** [comment]
you might want to use the @IterationsPerInvocation annotation btw :)

**Comment by j-baker** [comment]
In the best case for improvements there you're going between 150 million per second and 500 million; it seems to me you're going to be killed by Amdahl's law in practice - that's (on your laptop) probably the difference between 15 cycles per element and 5 cycles per element; the dominator is going to be basically anywhere the data is coming from

**Comment by j-baker** [comment]
idk it just doesn't seem you particularly win by doing this

**Comment by j-baker** [comment]
for reference we typically consider hashmaps to be fast, but a lookup is frequently a few hundred cycles

**Comment by jnelson15** [comment]
Where did 150mm come from? For the size 10k case it was between 15k-52k ops/s.

**Comment by j-baker** [comment]
I was multiplying those numbers by N to get time per element, since I would be surprised if writing 10 elements is 100k faster per element than writing a million.

**Comment by chrisalice** [comment]
I'm sorry, I should have been clearer: I meant benchmarks of real code, not microbenchmarks.
